// Temporarily disable player automation while retaining its implementation.
export const CLU_AUTOPLAY_ENABLED=false;
export const AUTOPLAY = Object.freeze({
  replanSeconds: 3,
  visionMeters: 350,
  stepMeters: 40,
  arrivalMeters: 5,
  maxReplyAgeSeconds: 2.5,
  turnGain: 2.5,
  aimGain: 3,
  confidence: 0.25,
  historySize: 40,
  continuationLeadSeconds: 0.8,
  minPlanSeconds: 0.4,
  waypointLeadSeconds: 0.35,
  speedBand: 0.5,
  turnSlowdownRadians: 1.3,
  targetSwitchRatio: 1.35,
  objectiveRetrySeconds: 15,
  turnBrakeRadians: 0.65,
  turnResumeRadians: 0.15,
  turboHeadingRadians: 0.08,
  turboMinSpeed: 10,
  nearbyObjectiveMeters: 2000,
  threatNearMeters: 100,
  threatApproachMeters: 250,
  threatClosingMetersPerSecond: 2,
  cornerCreepMeters: 2,
  cornerCreepSpeed: 2,
  cornerAimMeters: 0.02,
});
