import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1280,height:800},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const modelRequests=[];page.on('request',r=>{if(/(?:preti.*|tron_1982_solar_sailer)\.glb/.test(r.url()))modelRequests.push(r.url());});
 await page.route('**/*preti*glb*',async r=>{await new Promise(resolve=>setTimeout(resolve,1500));await r.continue();});
 await page.route('**/api/jev/**',r=>r.fulfill({status:503,body:'test'}));
 await page.goto('http://127.0.0.1:5173/?layoutSeed=1982&cycleStart=0');await page.waitForFunction(()=>window.__tron&&!document.querySelector('#start').disabled);
 assert.equal(modelRequests.length,0);
 console.log('Startup marks:',await page.evaluate(()=>performance.getEntriesByType('mark').filter(m=>m.name.startsWith('tron:')).map(m=>({name:m.name,ms:Math.round(m.startTime)}))));
 await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
 await page.waitForFunction(()=>__tron.state.arenaWaiting);
 await page.waitForFunction(()=>__tron.state.playerVehicle==='cycle');
 assert(modelRequests.length>=3);
 assert.equal(await page.evaluate(()=>__tron.state.won),false);
 await page.waitForFunction(()=>__tron.state.cycleRace.phase==='racing');
 // Clear the adjacent teammate's lane for the controls check. The close
 // formation otherwise puts its live trail directly across this first turn.
 await page.evaluate(()=>{const race=__tron.state.cycleRace;race.cycles[0].alive=false;for(let i=0;i<race.occupied.length;i++)if(race.occupied[i]===1)race.occupied[i]=0;__tron.place({cycleRace:race});});
 await page.keyboard.press('KeyD');await page.waitForFunction(()=>__tron.state.cycleRace.cycles[1].dir===3);
 await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>__tron.state.cycleRace.cycles[1].dir),3);
 await page.keyboard.press('KeyA');await page.waitForFunction(()=>__tron.state.cycleRace.cycles[1].dir===2);
 await page.waitForFunction(()=>['materialize','startup','launch','drive','drive-cabin','turn','explosion','wall-down','prepare-transport','transport','have-transport','entry-startup'].every(name=>__tron.state.audioSamples.includes('cycle-'+name)));
 const chargeBefore=await page.evaluate(()=>__tron.state.cycleRace.cycles[1].turboCharge);
 await page.keyboard.down('KeyW');await page.waitForTimeout(180);
 assert.equal(await page.evaluate(()=>__tron.state.cycleRace.cycles[1].boosting),true);
 const accelerating=await page.evaluate(()=>__tron.state.cycleRace.cycles[1].speedMultiplier);
 assert(accelerating>1&&accelerating<1.8,'turbo builds speed over time');
 assert(await page.evaluate(()=>__tron.state.cycleRace.cycles[1].turboCharge)<chargeBefore);
 await page.keyboard.up('KeyW');await page.waitForTimeout(80);
 assert.equal(await page.evaluate(()=>__tron.state.cycleRace.cycles[1].boosting),false);
 await page.keyboard.down('KeyS');await page.waitForTimeout(180);
 const decelerating=await page.evaluate(()=>__tron.state.cycleRace.cycles[1].speedMultiplier);
 assert(decelerating>.6&&decelerating<accelerating,'S reduces speed gradually');
 await page.keyboard.up('KeyS');
 assert.equal(await page.locator('#turbo span').textContent(),'W/T / TURBO');assert(await page.locator('#turbo').isVisible());
 const music=await page.evaluate(()=>__tron.state.music);assert.equal(music.paused,true);assert.equal(music.transition,null);
 await page.keyboard.press('Escape');const time=await page.evaluate(()=>__tron.state.cycleRace.time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__tron.state.cycleRace.time),time);
 await page.screenshot({path:'test-results/cycle-player.png'});
 await page.evaluate(()=>__tron.place({time:31}));
 await page.keyboard.press('Enter');
 await page.waitForTimeout(300);
 assert(!modelRequests.some(url=>url.includes('solar_sailer')));
 await page.evaluate(()=>{const r=__tron.state;__tron.place({cycleRace:{...r.cycleRace,phase:'result',winner:1,remaining:0}});});
 await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>__tron.state.crushed),false);
 await page.keyboard.press('Enter');await page.waitForFunction(()=>__tron.state.cycleRace.phase==='racing');
 await page.evaluate(()=>{const r=__tron.state;__tron.place({cycleRace:{...r.cycleRace,phase:'result',winner:0,remaining:0}});});
 await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>__tron.state.won),false);assert.deepEqual(errors,[]);
 await page.goto('http://127.0.0.1:5173/?layoutSeed=1982');
 await page.waitForFunction(()=>window.__tron&&!document.querySelector('#start').disabled);
 await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.waitForFunction(()=>__tron.state.playerVehicle==='cycle');
 assert.equal(await page.evaluate(()=>__tron.state.cycleAttemptsRemaining),3);
 assert.equal(await page.evaluate(()=>__tron.state.cycleRace.cycles[1].turboCharge),1);
 assert(await page.evaluate(()=>__tron.state.dataBeams.every(b=>b.collectedAt===null)));
 const guardBefore=await page.evaluate(()=>__tron.state.recognizers.find(e=>e.role==='arena-patrol'));
 await page.waitForTimeout(600);
 const guardAfter=await page.evaluate(()=>__tron.state.recognizers.find(e=>e.role==='arena-patrol'));
 assert(guardAfter.arenaPatrolling);assert(Math.hypot(guardAfter.x-guardBefore.x,guardAfter.s-guardBefore.s)>.1);
 await page.keyboard.press('Escape');const stopped=await page.evaluate(()=>__tron.state.recognizers.find(e=>e.role==='arena-patrol'));
 await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>__tron.state.recognizers.find(e=>e.role==='arena-patrol')),stopped);

 assert.deepEqual(errors,[]);
 console.log('Maze handoff, turbo, pause, music stop, manual retry, disabled endings and default arena test start passed.');
}finally{await browser.close();}
