import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,step,cannonPose,cannonTarget,updateWeapons} from '../src/simulation/run.js';
import {angleDelta,GUNNER,gunnerAimScale} from '../src/game/config.js';
function fixture(){const r=createRun();Object.assign(r,{x:-5000,s:-5000,yaw:0,gunner:true});r.recognizers=[];r.enemyTanks=[];return r;}
test('gunner aim holds world heading through hull turns; manual aim stays independent',()=>{const r=fixture();r.turretYaw=.7;for(let i=0;i<300;i++)step(r,{steer:1},1/60);assert.ok(Math.abs(angleDelta(.7,r.yaw+r.turretYaw))<1e-8);const old=r.yaw+r.turretYaw;step(r,{turret:1,steer:1,aimPitch:1},1/60);assert.ok(angleDelta(old,r.yaw+r.turretYaw)<0);assert.ok(r.aimPitch>0);});
test('manual gunner rounds follow sight elevation without target assistance',()=>{const r=fixture();r.aimPitch=.6;const p=cannonPose(r);updateWeapons(r,{fire:true},0);const shot=r.projectiles[0];assert.ok(Math.abs(Math.atan2(shot.vy,Math.hypot(shot.vx,shot.vs))-.6)<1e-8);assert.equal(shot.x,p.x);for(let i=0;i<600;i++)step(r,{aimPitch:1},1/60);assert.equal(r.aimPitch,GUNNER.maxPitch);for(let i=0;i<600;i++)step(r,{aimPitch:-1},1/60);assert.equal(r.aimPitch,GUNNER.minPitch);});

test('zoom scales horizontal and vertical aiming to preserve screen-space sensitivity',()=>{const samples=[0,1,2,3].map(gunnerZoom=>{const r=fixture();r.gunnerZoom=gunnerZoom;step(r,{turret:1,aimPitch:1},1/60);return r;});for(let z=1;z<4;z++){assert.ok(Math.abs(samples[z].turretYaw/samples[0].turretYaw-gunnerAimScale(z))<1e-8);assert.ok(Math.abs(samples[z].aimPitch/samples[0].aimPitch-gunnerAimScale(z))<1e-8);assert.ok(Math.abs(samples[z].turretYaw)<Math.abs(samples[z-1].turretYaw));}});

test('gunner aim accelerates, coasts to rest, and can reverse without snapping',()=>{const r=fixture();step(r,{turret:1,aimPitch:1},1/60);const first=r.gunnerYawMotion;assert.ok(first>0&&first<.5);for(let i=0;i<20;i++)step(r,{turret:1,aimPitch:1},1/60);assert.ok(r.gunnerYawMotion>.95);const before=r.turretYaw;step(r,{},1/60);assert.ok(r.gunnerYawMotion>0&&r.gunnerYawMotion<.9);assert.ok(r.turretYaw<before);for(let i=0;i<60;i++)step(r,{},1/60);assert.equal(r.gunnerYawMotion,0);assert.equal(r.gunnerPitchMotion,0);for(let i=0;i<30;i++)step(r,{turret:1},1/60);step(r,{turret:-1},1/60);assert.ok(r.gunnerYawMotion>0);for(let i=0;i<20;i++)step(r,{turret:-1},1/60);assert.ok(r.gunnerYawMotion<-.9);r.gunner=false;step(r,{},1/60);assert.equal(r.gunnerYawMotion,0);});

test('leveling returns elevation to the ground plane without changing azimuth; manual elevation cancels',()=>{const r=fixture();r.aimPitch=.6;r.turretYaw=.8;r.gunnerLeveling=true;step(r,{},1/60);assert.ok(r.aimPitch>0&&r.aimPitch<.6);for(let i=0;i<100;i++)step(r,{},1/60);assert.equal(r.aimPitch,0);assert.equal(r.gunnerLeveling,false);assert.ok(Math.abs(r.turretYaw-.8)<1e-8);r.aimPitch=.4;r.gunnerLeveling=true;step(r,{aimPitch:1},1/60);assert.equal(r.gunnerLeveling,false);assert.ok(r.aimPitch>.4);});

test('Clu rounds travel 825 meters and assisted fire reaches beyond the old range',()=>{const r=fixture();r.gunner=false;updateWeapons(r,{fire:true},0);assert.equal(r.projectiles[0].life,5);assert.equal(Math.hypot(r.projectiles[0].vx,r.projectiles[0].vs,r.projectiles[0].vy),165);const e={...createRun().recognizers[0],x:-5000,s:-4400,y:77,yaw:0,vx:0,vs:0,vy:0};r.recognizers=[e];r.projectiles=[];r.cooldown=0;assert.ok(cannonTarget(r).lock);for(let i=0;i<270;i++)updateWeapons(r,{fire:i===0},1/60);assert.equal(e.health,2);});
