import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:5173/');
 await page.waitForFunction(()=>window.__tron&&!document.querySelector('#start').disabled,null,{timeout:120000});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>__tron.state.mode==='running');
 await page.keyboard.press('KeyC');await page.keyboard.press('Home');
 await page.evaluate(()=>{__tron.configure({aiMode:'local'});});
 await page.keyboard.press('Space');
 await page.waitForFunction(()=>__tron.state.cycleRace.trails.length>6,null,{timeout:30000});
 await page.keyboard.press('Space');
 const race=await page.evaluate(()=>__tron.state.cycleRace);
 assert.equal(race.cycles.length,6);assert(race.trails.length>6);
 assert(await page.evaluate(()=>__tron.state.recognizers.some(e=>e.role==='arena-patrol')));
 assert(await page.evaluate(()=>__tron.state.cycleRendering.visible));
 await page.keyboard.down('KeyW');await page.waitForTimeout(5500);await page.keyboard.up('KeyW');
 await page.screenshot({path:'test-results/light-cycle-match.png'});
 await page.route('**/cycle-preview',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0;background:black"></body>'}));
 await page.goto('http://127.0.0.1:5173/cycle-preview');
 const stats=await page.evaluate(async()=>{
  const T=await import('/node_modules/three/build/three.module.js');
  const {loadLightCycles}=await import('/src/rendering/light-cycles.js');
  const {loadVehicles,cloneEnemyTank}=await import('/src/rendering/models.js');
  const [tank]=await loadVehicles(),enemy=cloneEnemyTank(tank);
  const appearance=root=>{const result=[];root.traverse(o=>{if(o.isMesh&&o.material?.color)result.push([o.material.name,o.material.color.getHex(),o.material.emissive?.getHex(),o.material.emissiveIntensity]);});return result;};
  const models=await loadLightCycles(),scene=new T.Scene();scene.background=new T.Color(0x030709);
  scene.add(new T.HemisphereLight(0xc9eaff,0x202030,3));const light=new T.DirectionalLight(0xffffff,3);light.position.set(2,6,4);scene.add(light);
  models.forEach((m,i)=>{m.position.x=(i-.5)*3;scene.add(m);});
  const renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(1440,900);document.body.append(renderer.domElement);
  const {LightCycleWalls}=await import('/src/rendering/light-cycle-walls.js');
  const {LIGHT_CYCLES:C}=await import('/src/game/light-cycles.js');
  const {createArenaFloor}=await import('/src/rendering/arena-floor.js');scene.add(createArenaFloor({elevationMeters:.02}));
  const walls=new LightCycleWalls(scene);
  const race={cycles:models.map((m,id)=>({id,alive:true})),trails:models.map((m,id)=>({bikeId:id,team:id,x1:m.position.x/C.cellMeters,z1:40/C.cellMeters,x2:m.position.x/C.cellMeters,z2:0}))};
  walls.update(race,1);
  if(walls.meshes.some(m=>m.material.transparent||!m.material.depthWrite))throw new Error('Cycle walls must be opaque');
  const {RecognizerShadows}=await import('/src/rendering/recognizer-shadows.js');
  const receivers=[];const crafts=models.map(root=>{const casters=[];root.traverse(o=>{if(o.isMesh){casters.push(o);receivers.push(o);}});return {root,casters,radius:2.6,distance:8};});
  const shadows=new RecognizerShadows(crafts,receivers,0,{size:512,prefix:'previewCycleShadow',darkness:.65,filterEdges:true,depthBias:.002});
  shadows.update(renderer);
  const camera=new T.PerspectiveCamera(45,1440/900,.1,100);camera.position.set(7,4,-10);camera.lookAt(0,.7,4);renderer.render(scene,camera);
  window.cyclePreview={renderer,scene,camera};
  return {sizes:models.map(m=>new T.Box3().setFromObject(m).getSize(new T.Vector3()).toArray()),tank:appearance(tank.root),enemy:appearance(enemy.root)};
 });
 assert.deepEqual(stats.tank,stats.enemy);assert(stats.sizes.every(s=>Math.abs(s[2]-3.6)<.01));
 await page.screenshot({path:'test-results/light-cycle-models.png'});
 await page.evaluate(()=>{const {renderer,scene,camera}=window.cyclePreview;camera.position.set(-7,1.4,1);camera.lookAt(-1.5,.75,.5);renderer.render(scene,camera);});
 await page.screenshot({path:'test-results/light-cycle-wheel-closeup.png'});
 assert.deepEqual(errors,[]);console.log('Six cycles racing, spectator pause/resume, arena patrol, imported model dimensions and matching tank materials passed.');
}finally{await browser.close();}
