import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:process.env.TRON_BROWSER_CHANNEL||'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:900}}), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>!document.querySelector('#start').disabled);
  await page.waitForFunction(()=>window.__tron?.state.mode==='ready');
  await page.waitForTimeout(900);
  const partial=await page.locator('#terminal-text').textContent();
  assert.equal(partial,'REQUEST ACCESS TO CLU PROGRAM\nCODE 6 PASSWORD TO MEMORY 0222');
  assert.equal(await page.locator('#terminal-actions').isVisible(),false);
  await page.screenshot({path:'test-results/terminal-typing.png'});
  assert.equal(await page.locator('#terminal-text').textContent(),'REQUEST ACCESS TO CLU PROGRAM\nCODE 6 PASSWORD TO MEMORY 0222');
  assert.equal(await page.evaluate(()=>window.__tron.state.mode),'ready');
  await page.screenshot({path:'test-results/terminal-complete.png'});
  await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.__tron.state.mode==='entering');
  const initial=await page.evaluate(()=>window.__tron.state);
  assert.equal(initial.recognizers.filter(e=>e.state==='pursue').length,2);
  await page.waitForFunction(()=>window.__tron.state.opening>.03);
  const high=await page.evaluate(()=>window.__tron.state.camera.y);
  await page.waitForTimeout(650);
  await page.screenshot({path:'test-results/opening-fade.png'});
  const tracking=await page.evaluate(()=>window.__tron.state);
  const pursuers=await page.evaluate(()=>window.__tron.state.recognizers.slice(0,2).map(e=>window.__tron.project({x:e.x,s:e.s,y:e.y})));
  for(const p of pursuers)assert.ok(Math.abs(p.x)<1&&Math.abs(p.y)<1&&p.z<1,JSON.stringify(p));
  const t=Math.max(0,Math.min(1,(tracking.opening-.15)/.85)),smooth=t*t*(3-2*t);
  assert.ok(Math.abs((tracking.camera.z+tracking.s)-(500+(19-500)*smooth))<1);
  assert.equal(await page.locator('.terminal-grid').count(),0);
  const cruising=await page.evaluate(()=>window.__tron.state);assert.equal(cruising.speed,22);assert.ok(cruising.s>initial.s);
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>window.__tron.state.mode),'paused');
  const paused=await page.evaluate(()=>window.__tron.state.opening),pausedTime=await page.evaluate(()=>window.__tron.state.time);
  await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__tron.state.opening),paused);
  assert.equal(await page.evaluate(()=>window.__tron.state.time),pausedTime);
  await page.keyboard.press('Enter');
  await page.waitForTimeout(1800);
  await page.screenshot({path:'test-results/opening-grid.png'});
  assert.ok(await page.evaluate(()=>window.__tron.state.camera.y)<high);
  const moving=await page.evaluate(()=>window.__tron.state);
  assert.ok(moving.time>initial.time);assert.equal(moving.x,initial.x);assert.ok(moving.s>initial.s);
  assert.ok(moving.recognizers.some((e,i)=>Math.hypot(e.x-initial.recognizers[i].x,e.s-initial.recognizers[i].s)>.1));
  await page.waitForFunction(()=>window.__tron.state.mode==='running');
  await page.screenshot({path:'test-results/opening-clu.png'});
  await page.evaluate(()=>__tron.place({turretYaw:Math.PI}));await page.waitForTimeout(1000);await page.screenshot({path:'test-results/recognizer-starting-line.png'});await page.evaluate(()=>__tron.place({turretYaw:0}));
  await page.evaluate(()=>__tron.reset());
  await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__tron.state.speed),22);
  await page.keyboard.down('KeyW');await page.keyboard.up('KeyW');
  await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>window.__tron.state.speed)<22);
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.reload();await page.waitForFunction(()=>!document.querySelector('#start').disabled);
  await page.waitForFunction(()=>window.__tron?.state.mode==='ready');
  assert.equal(await page.locator('#terminal-actions').isVisible(),false);
  await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.__tron.state.mode==='running');
  assert.equal(await page.evaluate(()=>window.__tron.state.opening),null);
  await page.reload();await page.waitForFunction(()=>!document.querySelector('#start').disabled);await page.waitForFunction(()=>window.__tron?.state.mode==='ready');
  await page.setViewportSize({width:640,height:700});
  await page.screenshot({path:'test-results/terminal-narrow.png'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  console.log('Terminal: incremental typing, Enter skip/start, grid reveal, camera descent, intro pause/resume, reduced-motion, narrow viewport passed.');
} finally {await browser.close();}
