import {chromium,webkit} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const expected=readFileSync(new URL('../docs/victory.txt',import.meta.url),'utf8').trimEnd();
const browser=await (process.env.TRON_BROWSER==='webkit'?webkit.launch({headless:true}):chromium.launch({channel:'chrome',headless:true}));
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/jev/decision',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"test"}'}));
 await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__tron&&!document.querySelector('#start').disabled);
 assert.equal(await page.locator('.terminal-encom').isVisible(),true);
 await page.screenshot({path:'test-results/terminal-encom.png'});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>__tron.state.mode==='running');
 await page.evaluate(()=>{const r=__tron.state;__tron.place({dataBeams:r.dataBeams.map(b=>({...b,collectedAt:r.time})),recognizers:[],enemyTanks:[],projectiles:[]});});
 await page.waitForFunction(()=>document.body.classList.contains('victory'));
 assert.equal(await page.evaluate(()=>__tron.state.crushed),false);
 await page.evaluate(()=>{window.printSamples=[];window.printSampleTimer=setInterval(()=>{window.printSamples.push({ms:performance.now(),count:document.querySelector('#terminal-text').textContent.length});},200);});
 await page.waitForFunction(text=>document.querySelector('#terminal-text').textContent===text,expected,{timeout:60000});
 const rates=await page.evaluate(()=>{clearInterval(window.printSampleTimer);const samples=window.printSamples;const rate=points=>(points.at(-1).count-points[0].count)*1000/(points.at(-1).ms-points[0].ms);const n=Math.floor(samples.length/3);return {early:rate(samples.slice(0,n)),late:rate(samples.slice(-n,-1))};});
 console.log('Printer characters/second:',rates);assert.ok(rates.early>30&&rates.late>30&&rates.early<50&&rates.late<50);
 const time=await page.evaluate(()=>__tron.state.time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__tron.state.time),time);
 assert.equal(await page.locator('#end-tribute').isVisible(),false);
 const bounds=await page.locator('.terminal-copy').boundingBox();assert.ok(bounds.y+bounds.height<=1000);
 assert.equal(await page.locator('.terminal-encom').isVisible(),true);
 await page.screenshot({path:'test-results/victory-terminal.png'});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.body.classList.contains('victory-credits'));
 await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'Enter',repeat:true,bubbles:true})));
 assert.equal(await page.evaluate(()=>document.body.classList.contains('victory-credits')),true);
 assert.equal(await page.locator('.terminal-copy').isVisible(),false);
 assert.equal(await page.locator('#terminal-text').textContent(),'');
 assert.equal(await page.evaluate(()=>__tron.state.music.track),'terminal');
 await page.waitForFunction(()=>document.querySelector('#tribute-text').textContent.length>0);
 assert.equal(await page.locator('.terminal-encom').isVisible(),true);
 await page.screenshot({path:'test-results/victory-credits.png'});
 await page.keyboard.press('Enter');await page.waitForFunction(()=>__tron.state.mode==='running');
 assert.equal(await page.evaluate(()=>document.body.classList.contains('victory-credits')),false);
 assert.equal(await page.evaluate(()=>__tron.state.won),false);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>__tron.state.mode==='paused');
 await page.keyboard.press('Shift+Digit8');await page.waitForFunction(()=>document.body.classList.contains('victory'));
 assert.equal(await page.evaluate(()=>__tron.state.won),true);
 assert.equal(await page.evaluate(()=>__tron.state.mode),'ready');
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.body.classList.contains('victory-credits'));
 assert.deepEqual(errors,[]);
 console.log('All-blue win freezes play, prints exact victory page, Return starts credits/music without detached message, and restart clears victory.');
}finally{await browser.close();}
