"""Trace blue roof footprints; requires opencv-python-headless. Outputs authored JS/SVG."""
from pathlib import Path
import cv2, json
root=Path(__file__).resolve().parents[1]
image=cv2.imread(str(root/'docs/references/images/mazes/Big labyrinth.png'))
b,g,r=cv2.split(image)
mask=((b>140)&(g>65)&(r<80)&(b.astype('int16')-r>90)).astype('uint8')*255
contours,hierarchy=cv2.findContours(mask,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_SIMPLE)
shapes=[]
for i,c in enumerate(contours):
 if hierarchy[0][i][3]!=-1 or cv2.contourArea(c)<12: continue
 def outline(c): return cv2.approxPolyDP(c,1.0,True).reshape(-1,2).tolist()
 holes=[]; child=hierarchy[0][i][2]
 while child!=-1:
  if cv2.contourArea(contours[child])>=8: holes.append(outline(contours[child]))
  child=hierarchy[0][child][0]
 shapes.append({'outline':outline(c),'holes':holes})
shapes.sort(key=lambda p:(min(v[1] for v in p['outline']),min(v[0] for v in p['outline'])))
h,w=mask.shape
(root/'src/levels/labyrinth-outlines.js').write_text('// Generated by scripts/trace-labyrinth.py from the supplied Big labyrinth.png.\nexport const BLUEPRINT_SIZE='+json.dumps([w,h])+';\nexport const METERS_PER_PIXEL=2.4;\nexport const SHAPES='+json.dumps(shapes,separators=(',',':'))+';\n')
paths=[]
for p in shapes:
 d=' '.join('M'+' L'.join(f'{x},{y}' for x,y in ring)+' Z' for ring in [p['outline']]+p['holes'])
 paths.append(f'<path d="{d}"/>')
(root/'docs/references/labyrinth-trace.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}"><image href="images/mazes/Big%20labyrinth.png" width="{w}" height="{h}"/><g fill="none" stroke="#ffdf77" stroke-width="1.5">'+''.join(paths)+'</g></svg>')
print(f'{len(shapes)} islands, {sum(len(p["holes"]) for p in shapes)} holes, {sum(len(p["outline"]) for p in shapes)} vertices')
